config/routes.rb
Rails.application.routes.draw do
 
  devise_for :views
  resources :results
  resources :responses
  resources :survey_questions
  resources :surveys
  resources :consumers

  get '/', to: 'intro#info'
  devise_for :consumers

end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	has_many :surveys

	devise :database_authenticatable, :registerable
    #     	:recoverable, :rememberable, :trackable, :validatable

end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  before_action :set_consumer, only: [:show, :edit, :update, :destroy]

  # GET /consumers
  # GET /consumers.json
  def index
    @consumers = Consumer.all
  end

  # GET /consumers/1
  # GET /consumers/1.json
  def show
  end

  # GET /consumers/new
  def new
    @consumer = Consumer.new
  end

  # GET /consumers/1/edit
  def edit
  end

  # POST /consumers
  # POST /consumers.json
  def create
    @consumer = Consumer.new(consumer_params)

    respond_to do |format|
      if @consumer.save
        format.html { redirect_to @consumer, notice: 'Consumer was successfully created.' }
        format.json { render :show, status: :created, location: @consumer }
      else
        format.html { render :new }
        format.json { render json: @consumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consumers/1
  # PATCH/PUT /consumers/1.json
  def update
    respond_to do |format|
      if @consumer.update(consumer_params)
        format.html { redirect_to @consumer, notice: 'Consumer was successfully updated.' }
        format.json { render :show, status: :ok, location: @consumer }
      else
        format.html { render :edit }
        format.json { render json: @consumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumers/1
  # DELETE /consumers/1.json
  def destroy
    @consumer.destroy
    respond_to do |format|
      format.html { redirect_to consumers_url, notice: 'Consumer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumer
      @consumer = Consumer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consumer_params
      params.require(:consumer).permit(:consumer_id, :ip_address, :email, :clave)
    end
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/views/consumers/_form.html.erb
<%= form_for(@consumer) do |f| %>
  <% if @consumer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consumer.errors.count, "error") %> prohibited this consumer from being saved:</h2>

      <ul>
      <% @consumer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :ip_address, :value => request.remote_ip, :readonly => true %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
    <!-- Modification for Tinymce  -->
    <!-- f.text_area :email, :class => "tinymce", :rows => 40, :cols => 120  -->
  </div>
  <div class="field">
    <label for="clave">Password</label>
    <%= f.password_field :clave %>
  </div>
  <div class="actions">
    <%= f.submit  :class => 'btn' %>
  </div>
<% end %>

app/views/consumers/edit.html.erb
<h1>Editing Consumer</h1>

<%= render 'form' %>

<%= link_to 'Show', @consumer %> |
<%= link_to 'Back', consumers_path %>

app/views/consumers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Consumers</h1>

<table>
  <thead>
    <tr>
      <th>Consumer</th>
      <th>Ip address</th>
      <th>Email</th>
      <th>Clave</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consumers.each do |consumer| %>
      <tr>
        <td><%= consumer.consumer_id %></td>
        <td><%= consumer.ip_address %></td>
        <td><%= consumer.email %></td>
        <td><%= consumer.clave %></td>
        <td><%= link_to 'Show', consumer %></td>
        <td><%= link_to 'Edit', edit_consumer_path(consumer) %></td>
        <td><%= link_to 'Destroy', consumer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consumer', new_consumer_path %>

app/views/consumers/new.html.erb
<h1>New Consumer</h1>

<%= render 'form' %>

<%= link_to 'Back', consumers_path %>

app/views/consumers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Consumer:</strong>
  <%= @consumer.consumer_id %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @consumer.ip_address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @consumer.email %>
</p>

<p>
  <strong>Clave:</strong>
  <%= @consumer.clave %>
</p>

<%= link_to 'Edit', edit_consumer_path(@consumer) %> |
<%= link_to 'Back', consumers_path %>